### ISSUE TITLE
Тесты в либе падают

### ISSUE THREAD

**Issue by kirillkostrov** [surfstudio/surf-compose-forms#27]
testEmojiFilter() падает
```
java.lang.AssertionError: [❤️‍🩹, ❤‍🩹, 🫀, 🫁, 🫂, 🪶, 🪲, 🪳, 🪰, 🪱, 🪴, 🫐, 🫒, 🫑, 🫓, 🫔, 🫕, 🫖, 🪨, 🪵, 🪂, 🪐, 🪀, 🪁, 🪄, 🪅, 🪆, 🪡, 🪢, 🩱, 🩲, 🩳, 🩴, 🩰, 🪖, 🪗, 🪕, 🪘, 🪔, 🪙, 🪓, 🪃, 🪚, 🪛, 🪝, 🪜, 🩸, 🩹, 🩺, 🪞, 🪟, 🪑, 🪠, 🪤, 🪒, 🪣, 🪥, 🪦, 🪧] is not empty
	at ru.surfstudio.compose.forms.test.EmojiFilterTests.filterEmoji(EmojiFilterTests.kt:39)
```
testEmojiPredicate() падает
```
java.lang.AssertionError: [🫀, 🫁, 🫂, 🪶, 🪲, 🪳, 🪰, 🪱, 🪴, 🫐, 🫒, 🫑, 🫓, 🫔, 🫕, 🫖, 🪨, 🪵, 🪂, 🪐, 🪀, 🪁, 🪄, 🪅, 🪆, 🪡, 🪢, 🩱, 🩲, 🩳, 🩴, 🩰, 🪖, 🪗, 🪕, 🪘, 🪔, 🪙, 🪓, 🪃, 🪚, 🪛, 🪝, 🪜, 🩸, 🩹, 🩺, 🪞, 🪟, 🪑, 🪠, 🪤, 🪒, 🪣, 🪥, 🪦, 🪧] is not empty
	at ru.surfstudio.compose.forms.test.EmojiFilterTests.filterEmoji(EmojiFilterTests.kt:39)
```

**Comment by kirillkostrov** [comment]
Please distegard my comment about testRemove()
